### ISSUE TITLE
Cider+Figwheel doesn't work with fresh project

### ISSUE THREAD

**Issue by rbuchmann** [gadfly361/reagent-figwheel#10]
Hi, I created a project with 

``` bash
lein new reagent-figwheel foo +cider +test +devtools +routes
```

I then went to a source buffer, did cider-jack-in-clojurescript. It launches and runs the configured commands, but I get 

```
No such namespace: foo.core, could not locate foo/core.cljs, foo/core.cljc, or Closure namespace "foo.core" 
```

I assume that for this to work, the cljs directories also need to be on the source-path?

**Comment by gadfly361** [comment]
@rbuchmann I created a new project with the command above, and cider seems to work just fine.

Can you confirm that you have this:

**Comment by rbuchmann** [comment]
@gadfly361 Yes, that's exactly what I have in my init file and what gets run. I am using 
```
CIDER 0.15.1snapshot (package: 20170905.1037)
nREPL 0.2.12
refactor-nrepl 2.4.0-SNAPSHOT
emacs 25.2.1
```
It works if I add "src/cljs" to :source-paths.

**Comment by rbuchmann** [comment]
I found the reason... I used underscores in the project name, so the example I posted was a bit misleading, just like the error message m-)
It works with hyphens. Sorry for the trouble,

**Comment by gadfly361** [comment]
No trouble! Glad you were able to resolve this :)
