### ISSUE TITLE
Add Warning About Reagent Gotcha

### ISSUE THREAD

**Issue by mike-thompson-day8** [gadfly361/reagent-figwheel#2]
This is an easy mistake to make:
https://github.com/reagent-project/reagent/issues/112

I wonder if this template should contain a comment warning the programmer about this issue, including perhaps a link to the docs?

**Comment by gadfly361** [comment]
Thanks for the heads up!  I'm likely not understanding the problem itself, but I wasn't able to reproduce it with reagent-figwheel.  Made a comment in https://github.com/reagent-project/reagent/issues/112, waiting to hear back.

**Comment by gadfly361** [comment]
closing this given what @mike-thompson-day8  said in https://github.com/reagent-project/reagent/issues/112 about remounting root component
